STM32Cube Expansion Pack CAN Stack: CanIf Class Reference
CanIf Class Reference
CAN Interface Module
the class to work on the CAN controller interface
#include <CanIf.h>
Public Member Functions
CanIf ()
~CanIf ()
Std_ReturnType Init (void)
init of the CanIf module
Std_ReturnType Start (void)
all init of the CanIf module is done
Std_ReturnType Transmit (CanIf_TxPduIdType txPduId, const CanIf_PduInfoType *ptr2PduInfo)
Requests transmission of a PDU using the Tx software Buffer.
Std_ReturnType Transmit (ComStack_PduType txPduId, const ComStack_PduInfoType *ptr2PduInfo)
Requests transmission of a PDU using the Tx software Buffer.
Std_ReturnType Transmit (ComStack_CanMsgHeader msgHeader, const uint8_t *ptr2Data)
Requests transmission of a PDU using the Tx software Buffer.
Std_ReturnType Receive (CanIf_RxPduIdType rxPduId, const CanIf_PduInfoType *ptr2PduInfo)
poll the RxBuffer for a message
Std_ReturnType Receive (ComStack_PduType rxPduId, const ComStack_PduInfoType *ptr2PduInfo)
poll the RxBuffer for a message
Std_ReturnType Receive (REF2VAR(ComStack_CanMsgHeader, AUTOMATIC) msgHeader, const uint8_t *ptr2Data)
poll the RxBuffer for a message
Std_ReturnType ConnectUpperLayerIndication (ComStack_PduType rxPduId, const CanIfUpperLayer *p2UpperLayerObject)
we need to know the connected upper layer object for rx indication
ComStack_PduType GetIfRxPduName (CanIf_UpperLayerType upperLayerName, ComStack_PduType rxPduId)
to get the CanIf_RxPduIdType name
ComStack_PduType GetIfTxPduName (CanIf_UpperLayerType upperLayerName, ComStack_PduType txPduId)
to get the CanIf_TxPduIdType name
void TxTask (void)
task function to push the tx message from software buffer to tx mailbox
Public Member Functions inherited from ComIf
ComIf (ComInterfaceType ComIfType)
constructor to initialize the interface type value
ComInterfaceType GetComIfType (void)
get the type of communication controller interface
Private Member Functions
Std_ReturnType FindFreeFilter (const uint8_t *ptr2FilterBankNumber, const uint8_t *ptr2FilterNumber, const uint8_t *ptr2FilterMode)
to find a free CAN hardware filter
Std_ReturnType SetFilterByBitmask (ECU_CanController Controller, ComStack_CanIdType FilterId, ComStack_CanIdType FilterMask)
configure a free hardware filter using bit masking
int SetFilterByCanId (ECU_CanController Controller, ComStack_CanIdType FilterId)
configure a free hardware filter using single CAN Id filtering
uint32_t CanIdToHalFormat (ComStack_CanIdType CanId)
change the 32bit format to use with STM Registers
Private Member Functions inherited from TME_VersionInfo
TME_VersionInfo (uint8_t Module, uint8_t Version, uint8_t Patch)
constructor to set version Ids
TME_VersionInfo (uint8_t Vendor, uint8_t Module, uint8_t Version, uint8_t Patch)
constructor to set version Ids including the vendor
TME_VersionInfo (const TME_VersionInfo &other)
copy constructor
Private Attributes
CanIfStates state = CanIfStates::PreInit
CAN_HandleTypeDef bxCanHdl [2]
we need a handle to hold the information for the bxCAN controller
CAN_TxMessage canTxBufferMirror
STM_HAL_TxHeaderTypeDef txHeaderList [CANIF_TXPDU_COUNT]
We create a list with CAN message headers for fast access sorted by the CanIf_txPduIdType.
ComStack_CanMsgHeader rxHeaderList [CANIF_RXPDU_COUNT]
We create a list with CAN message headers for fast access sorted by the CanIf_rxPduIdType.
Additional Inherited Members
Public Types inherited from ComIf
enum ComInterfaceType { ComInterfaceType::ComIfUnknown = 0, ComInterfaceType::CanIf, ComInterfaceType::TwiIf, ComInterfaceType::FlexRayIf }
naming the known interface classes
Detailed Description
the class to work on the CAN controller interface
Gemäß dem AUTOSAR Gedanken abstrahiert das CAN Interface die gesamte CAN Hardware. Es wird also später auch nur ein CanIf Objekt geben.
Genauso wird diese CanIf Objekt global angelegt sein.
Todo:
es braucht eine Absicherung auf nur ein Objekt
Definition at line 127 of file CanIf.h.
Constructor & Destructor Documentation
CanIf()
CanIf::CanIf ()
Standard constructor will do a connection to the precompile configuration
~CanIf()
CanIf::~CanIf ()
Destructor shouldn't called on an embedded system
Member Function Documentation
CanIdToHalFormat()
uint32_t CanIf::CanIdToHalFormat (ComStack_CanIdType CanId) private
change the 32bit format to use with STM Registers
we use the unified CanIf_CanIdSelectType for easy remapping
this function or the union can be changed to match register on other controller
Parameters
[in] CanId should be a CanIf formated CanId
Returns
CanId in STM Register format
Definition at line 785 of file CanIf.cpp.
References CanIf_CanIdSelectType::common, CanIf_STM_StdCanIdType::Id11bit, CanIf_STM_ExtCanIdType::Id29bit, CanIf_STM_ExtCanIdType::IDE, CanIf_STM_ExtCanIdType::RTR, CanIf_CanIdSelectType::stm_ExtId, CanIf_CanIdSelectType::stm_StdId, and TRUE.
Referenced by SetFilterByBitmask(), and SetFilterByCanId().
FindFreeFilter()
Std_ReturnType CanIf::FindFreeFilter (const uint8_t * ptr2FilterBankNumber, const uint8_t * ptr2FilterNumber, const uint8_t * ptr2FilterMode) private
to find a free CAN hardware filter
STM hasn't a function like this in the HAL.
We find a free hardware filter and returns the filter bank to use the filter.
We returns the filter number to use it on fast selection in IRQ routine.
The filter mode is used to search for mask or identifier filter. If searching for identifier filter we returns also if there is a FR2 is empty
Parameters
[out] ptr2FilterBankNumber returns the number of the first free filter bank
[out] ptr2FilterNumber returns the filter number according to the previous filter configuration
[in,out] ptr2FilterMode selects the search for Mask filter (aka deactivated filter) or Identifier Filter. on Identifier Filter search it returns if the FR1 register is already in use
Returns
E_OK ........... we found an unused filter
E_NOT_OK ........... we can't find an unused filter
Todo:
we need a readable implementation for the "second identifier filter bit" inside ptr2FilterMode
Definition at line 618 of file CanIf.cpp.
References AUTOMATIC, bxCanHdl, CANIF_MAX_NUMBER_OF_FILTER, CanMasterController, E_NOT_OK, E_OK, FALSE, P2VAR, and TRUE.
Referenced by SetFilterByBitmask(), and SetFilterByCanId().
SetFilterByBitmask()
Std_ReturnType CanIf::SetFilterByBitmask (ECU_CanController Controller, ComStack_CanIdType FilterId, ComStack_CanIdType FilterMask) private
configure a free hardware filter using bit masking
set hardware filter
Attention
This isn't the same like inside STM register access. But the function manages the correct use for STM HAL
bit 31 is IDE
bit 30 is RTR
Parameters
[in] Controller select the controller where the filter should be applied
[in] FilterId the selected filter bits
[in] FilterMask the filter mask to select valid filter bits
Returns
E_OK if the filter is applied, E_NOT_OK no hardware filter free
Todo:
we need a handling to select different Rx Fifo
Definition at line 676 of file CanIf.cpp.
References bxCanHdl, CanIdToHalFormat(), CanMasterController, E_NOT_OK, E_OK, and FindFreeFilter().
SetFilterByCanId()
int CanIf::SetFilterByCanId (ECU_CanController Controller, ComStack_CanIdType FilterId) private
configure a free hardware filter using single CAN Id filtering
set hardware filter
Parameters
[in] Controller select the controller where the filter should be applied
[in] FilterId the selected filter bits
Returns
E_OK if the filter is applied, E_NOT_OK no hardware filter free
Todo:
we need a handling to select different Rx Fifo
Definition at line 727 of file CanIf.cpp.
References bxCanHdl, CanIdToHalFormat(), CanMasterController, E_NOT_OK, E_OK, and FindFreeFilter().
TxTask()
void CanIf::TxTask (void)
task function to push the tx message from software buffer to tx mailbox
Todo:
the Tx Task need handling to transmit to other CAN controller then the bxCanMaster
Definition at line 570 of file CanIf.cpp.
References bxCanHdl, CANIF_TX_BUFFER_SIZE, CanMasterController, Ready, and state.
Member Data Documentation
bxCanHdl
CAN_HandleTypeDef CanIf::bxCanHdl[2] private
we need a handle to hold the information for the bxCAN controller
Todo:
there are STM controller with three CAN controller too!!!
Definition at line 327 of file CanIf.h.
Referenced by FindFreeFilter(), Init(), SetFilterByBitmask(), SetFilterByCanId(), and TxTask().
canTxBufferMirror
CAN_TxMessage CanIf::canTxBufferMirror private
a semi static place to bring messages from buffer to hardware
Definition at line 330 of file CanIf.h.
rxHeaderList
ComStack_CanMsgHeader CanIf::rxHeaderList[CANIF_RXPDU_COUNT] private
We create a list with CAN message headers for fast access sorted by the CanIf_rxPduIdType.
on rx we can use the the ComStack type (in contrast to STM HAL type) on pre compiled linking that could be on FLASH
Definition at line 342 of file CanIf.h.
state
CanIfStates CanIf::state = CanIfStates::PreInit private
we have a simple state machine inside
Definition at line 323 of file CanIf.h.
Referenced by Init(), Start(), Transmit(), and TxTask().
txHeaderList
STM_HAL_TxHeaderTypeDef CanIf::txHeaderList[CANIF_TXPDU_COUNT] private
We create a list with CAN message headers for fast access sorted by the CanIf_txPduIdType.
we use the STM-CAN-Message-Headers for fast copy during tx. Maybe we change this later on pre compiled linking that could be on FLASH
Definition at line 336 of file CanIf.h.
The documentation for this class was generated from the following files:
E:/Embedded_SourceCode/STM32IDE_ws/NucleoCanDev/Drivers/BSP/TM_Engineering_board/CanIf/CanIf.h
E:/Embedded_SourceCode/STM32IDE_ws/NucleoCanDev/Drivers/BSP/TM_Engineering_board/CanIf/CanIf.cpp