STM32Cube Expansion Pack CAN Stack: CanIfUpperLayer Class Reference
CanIfUpperLayer Class Reference
Unified interface OSI Layer 2 to Layer 3
#include <CanIfUpperLayer.h>
Public Member Functions
virtual Std_ReturnType RxIndication (ComStack_PduType rxPduId, const ComStack_CanMessageType *ptr2Sdu)
virtual function declaration to have an indication function in all upper layer classes
virtual Std_ReturnType RxIndication (ComStack_PduType rxPduId, REF2CONST(ComStack_CanMsgHeader, AUTOMATIC) CanMsgHeader, REF2CONST(ComStack_PduInfoType, AUTOMATIC) PduInfo)
virtual function declaration to have an indication function in all upper layer classes
Detailed Description
a class with the standard interface of the upper transport layer classes
Todo:
maybe we should bring this to a template
Definition at line 55 of file CanIfUpperLayer.h.
Member Function Documentation
RxIndication() [1/2]
virtual Std_ReturnType CanIfUpperLayer::RxIndication (ComStack_PduType rxPduId, const ComStack_CanMessageType * ptr2Sdu) inline virtual
virtual function declaration to have an indication function in all upper layer classes
Parameters
[in] rxPduId naming the incoming message
[in] ptr2Sdu pointer to the data unit
Reimplemented in CanFT2p0, IsoTp, and CanFT2p0Stream.
Definition at line 63 of file CanIfUpperLayer.h.
References E_NOT_OK.
Referenced by RxIndication(), and CanIf::RxIndication().
RxIndication() [2/2]
Std_ReturnType CanIfUpperLayer::RxIndication (ComStack_PduType rxPduId, REF2CONST(ComStack_CanMsgHeader, AUTOMATIC) CanMsgHeader, REF2CONST(ComStack_PduInfoType, AUTOMATIC) PduInfo) virtual
virtual function declaration to have an indication function in all upper layer classes
Parameters
[in] rxPduId naming the incoming message
[in] CanMsgHeader reference to the CanMsgHeader
[in] PduInfo reference to the data unit
Definition at line 27 of file CanIfUpperLayer.cpp.
References AUTOMATIC, E_NOT_OK, RxIndication(), and VAR.
The documentation for this class was generated from the following files:
E:/Embedded_SourceCode/STM32IDE_ws/NucleoCanDev/Drivers/BSP/TM_Engineering_board/CanIf/CanIfUpperLayer.h
E:/Embedded_SourceCode/STM32IDE_ws/NucleoCanDev/Drivers/BSP/TM_Engineering_board/CanIf/CanIfUpperLayer.cpp