STM32Cube Expansion Pack CAN Stack: API function definitions for CAN Interface Module
API function definitions for CAN Interface Module
CAN Interface Module
Functions used in the API.
Macros
#define CANIF_INIT_ID (0x01)
service ID of CanIf::Init()
Functions
Std_ReturnType CanIf::Init (void)
init of the CanIf module
Std_ReturnType CanIf::Start (void)
all init of the CanIf module is done
Std_ReturnType CanIf::Transmit (CanIf_TxPduIdType txPduId, const CanIf_PduInfoType *ptr2PduInfo)
Requests transmission of a PDU using the Tx software Buffer.
Std_ReturnType CanIf::Transmit (ComStack_PduType txPduId, const ComStack_PduInfoType *ptr2PduInfo)
Requests transmission of a PDU using the Tx software Buffer.
Std_ReturnType CanIf::Transmit (ComStack_CanMsgHeader msgHeader, const uint8_t *ptr2Data)
Requests transmission of a PDU using the Tx software Buffer.
Std_ReturnType CanIf::Receive (CanIf_RxPduIdType rxPduId, const CanIf_PduInfoType *ptr2PduInfo)
poll the RxBuffer for a message
Std_ReturnType CanIf::Receive (ComStack_PduType rxPduId, const ComStack_PduInfoType *ptr2PduInfo)
poll the RxBuffer for a message
Std_ReturnType CanIf::Receive (REF2VAR(ComStack_CanMsgHeader, AUTOMATIC) msgHeader, const uint8_t *ptr2Data)
poll the RxBuffer for a message
Std_ReturnType CanIf::ConnectUpperLayerIndication (ComStack_PduType rxPduId, const CanIfUpperLayer *p2UpperLayerObject)
we need to know the connected upper layer object for rx indication
ComStack_PduType CanIf::GetIfRxPduName (CanIf_UpperLayerType upperLayerName, ComStack_PduType rxPduId)
to get the CanIf_RxPduIdType name
ComStack_PduType CanIf::GetIfTxPduName (CanIf_UpperLayerType upperLayerName, ComStack_PduType txPduId)
to get the CanIf_TxPduIdType name
Detailed Description
Functions used in the API.
Function Documentation
ConnectUpperLayerIndication()
Std_ReturnType CanIf::ConnectUpperLayerIndication (ComStack_PduType rxPduId, const CanIfUpperLayer * p2UpperLayerObject) virtual
we need to know the connected upper layer object for rx indication
maybe we solve this in a static way on code generation later
Parameters
[in] rxPduId to name the rx pdu
[in] p2UpperLayerObject to give the pointer to the object
Implements ComIf.
Definition at line 552 of file CanIf.cpp.
References E_NOT_OK, E_OK, NULL_PTR, and p2UpperLayerList.
Init()
Std_ReturnType CanIf::Init (void)
init of the CanIf module
This will start the hardware modules
See also
CANIF_INIT_ID
Warning
here will be done the unique connection to the interrupt handles we need a good C++ way for this
Todo:
we need a generic mode for IRQ activation
Todo:
MyTest_RxPduConfig[InitPdu].N_PDU_Name -->> muss noch zu geordnet werden !!!
Definition at line 132 of file CanIf.cpp.
References CanControllerParaType::AutoBusOff, CanControllerParaType::AutoRetransmission, CanControllerParaType::AutoWakeUp, CanIf::bxCanHdl, Can_NucleoConfig, CanBaudrate_unknown, CanControllerBaudrateConfigType::CanControllerPrescaler, CanControllerBaudrateConfigType::CanControllerSeg1, CanControllerBaudrateConfigType::CanControllerSeg2, CanControllerBaudrateConfigType::CanControllerSyncJumpWidth, CANIF_DET_REPORTERROR, CANIF_INIT_ID, CanMasterController, CanSlaveController, controllerList, E_INIT_FAILED, E_NOT_OK, ErrorState, HwInit, CanControllerParaType::InitBaudrate, CanControllerParaType::Instance, CanControllerParaType::Mode, ptr2Can1Hdl, CanConfigType::ptr2CanBaudrateConfigSet, CanConfigType::ptr2CanParaConfigSet, CanControllerParaType::ReceiveFifoLocked, CanIf::state, CanControllerParaType::TransmitFifoPriority, and CanControllerParaType::TTMode.
Receive() [1/3]
Std_ReturnType CanIf::Receive (CanIf_RxPduIdType rxPduId, const CanIf_PduInfoType * ptr2PduInfo)
poll the RxBuffer for a message
This function looks if there is an message inside the buffer by checking the PDU name
This is the AUTOSAR like function CanIf_ReadRxPduData
Parameters
[in] rxPduId search for the PDU by using the CanIf_RxPduIdType
[out] ptr2PduInfo to return the data
Todo:
this is a fix not save implementation
Definition at line 458 of file CanIf.cpp.
References ComStack_CanMsgHeader::CanId, ComStack_CanMessageType::CanIf_Header, tCAN_RxMessage::CanIf_Message, CANIF_RX_BUFFER_SIZE, CanIf_RxMessage_free, CanIf_RxMessage_rdy2rd, CanIf_RxMessage_read, canRxBuffer, ComStack_CanMessageType::Data, ComStack_CanMsgHeader::DLC, E_NOT_OK, E_OK, CanIf_RxBufferType::ptr2MsgBuffer, and tCAN_RxMessage::State.
Referenced by CanIf::Receive().
Receive() [2/3]
Std_ReturnType CanIf::Receive (ComStack_PduType rxPduId, const ComStack_PduInfoType * ptr2PduInfo) virtual
poll the RxBuffer for a message
This function remaps the pure virtual function coming from the ComIf class
This is the AUTOSAR like function CanIf_ReadRxPduData
Parameters
[in] rxPduId search for the PDU by using the CanIf_RxPduIdType
[out] ptr2PduInfo to return the data
Implements ComIf.
Definition at line 395 of file CanIf.cpp.
References CanIf::Receive().
Receive() [3/3]
Std_ReturnType CanIf::Receive (REF2VAR(ComStack_CanMsgHeader, AUTOMATIC) msgHeader, const uint8_t * ptr2Data)
poll the RxBuffer for a message
This function looks if there is an message inside the buffer with the requested CAN ID (including IDE & RTR)
Parameters
[in,out] msgHeader we need the CanId to look for the message
[out] ptr2Data pointer to return the data -> we need a C++ save way
Todo:
this is a fix not save implementation
Definition at line 404 of file CanIf.cpp.
References ComStack_CanMsgHeader::CanId, ComStack_CanMessageType::CanIf_Header, tCAN_RxMessage::CanIf_Message, CANIF_RX_BUFFER_SIZE, CanIf_RxMessage_rdy2rd, canRxBuffer, E_NOT_OK, CanIf_RxBufferType::ptr2MsgBuffer, and tCAN_RxMessage::State.
Start()
Std_ReturnType CanIf::Start (void)
all init of the CanIf module is done
This will start the interface modules
Definition at line 292 of file CanIf.cpp.
References E_NOT_OK, E_OK, Ready, and CanIf::state.
Transmit() [1/3]
Std_ReturnType CanIf::Transmit (CanIf_TxPduIdType txPduId, const CanIf_PduInfoType * ptr2PduInfo)
Requests transmission of a PDU using the Tx software Buffer.
returns E_NOT_OK if SW buffer full
this function is the AUTOSAR like transmit function
Parameters
[in] txPduId name the Pdu to transmit
[in] ptr2PduInfo pointer to the data to transmit
Returns
Std_ReturnType
Todo:
we should rework to select the CAN Channel by using PDU IDs
Definition at line 359 of file CanIf.cpp.
References E_NOT_OK.
Referenced by CanIf::Transmit(), and CanFT2p0::TxIndication().
Transmit() [2/3]
Std_ReturnType CanIf::Transmit (ComStack_CanMsgHeader msgHeader, const uint8_t * ptr2Data)
Requests transmission of a PDU using the Tx software Buffer.
this function is we send messages without a transport protocol, maybe for test messages
returns E_NOT_OK if SW buffer full
Parameters
[in] msgHeader Header for the CAN message handling
[in] ptr2Data pointer to the data to transmit
Returns
Std_ReturnType
Definition at line 318 of file CanIf.cpp.
References CANIF_TX_BUFFER_SIZE, E_NOT_OK, Ready, and CanIf::state.
Transmit() [3/3]
Std_ReturnType CanIf::Transmit (ComStack_PduType txPduId, const ComStack_PduInfoType * ptr2PduInfo) virtual
Requests transmission of a PDU using the Tx software Buffer.
returns E_NOT_OK if SW buffer full
This function remaps the pure virtual function coming from the ComIf class
Parameters
[in] txPduId name the Pdu to transmit
[in] ptr2PduInfo pointer to the data to transmit
Returns
Std_ReturnType
Todo:
we should rework to select the CAN Channel by using PDU IDs
Implements ComIf.
Definition at line 310 of file CanIf.cpp.
References CanIf::Transmit().